In [1]:
import  numpy as np


In [7]:
arr = np.array([1,4,5,3,2])
brr = np.array([2,3,4,3,2])
# crr = arr+brr
# print(crr)
crr = np.add(arr,brr)
print(crr)

[3 7 9 6 4]


In [11]:
arr = np.array([1,4,5,3,2])
brr = np.array([2,3,4,3,2])
crr = np.subtract(arr,brr)
print(crr)

[-1  1  1  0  0]


In [9]:
arr = np.array([1,4,5,3,2])
brr = np.array([2,3,4,3,2])
# crr = arr*brr
# print(crr)
crr = np.multiply(arr,brr)
print(crr)


[ 2 12 20  9  4]


In [12]:
arr = np.array([1,4,5,3,2])
brr = np.array([2,3,4,3,2])
crr = np.divide(arr,brr)
print(crr)

[0.5        1.33333333 1.25       1.         1.        ]


In [17]:
# matrix mutliplications
arr = [[1,2,3,4],
       [5,6,7,8]]
brr = [[1,2],
      [3,4],
       [5,6],
       [7,8]]

crr = np.dot(arr,brr)
print(crr)

[[ 50  60]
 [114 140]]
