In [1]:
import numpy as np

In [4]:
arr = np.array([1,10,20,13,23,43,323,42,33,87,45,332,32])
print(arr)
print(arr.ndim)
print(arr.dtype)

[  1  10  20  13  23  43 323  42  33  87  45 332  32]
1
int64


In [9]:
arr = np.array([1,10,20,13,23,43,323,42,33,87,45,332,32])
# indexing 
print(arr[3])
print(arr[10])
print(arr[-3])
print(arr[8])



13
45
45
33


In [17]:
# slicing 
arr = np.array([1,10,20,13,23,43,323,42,33,87,45,332,32])
print(arr[1:10])
print(arr[0:4])
print(arr[0:])
print(arr[:len(arr)+1])
print(arr[-5:-1])
print(arr[-10:])


[ 10  20  13  23  43 323  42  33  87]
[ 1 10 20 13]
[  1  10  20  13  23  43 323  42  33  87  45 332  32]
[  1  10  20  13  23  43 323  42  33  87  45 332  32]
[ 33  87  45 332]
[ 13  23  43 323  42  33  87  45 332  32]
