In [1]:
import numpy as np

In [11]:
import numpy as np  # Importing the numpy library

# Create a 1D array with 12 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the array to have 3 rows and 4 columns (3x4 matrix)
reshaped_array = arr.reshape((3, 4))

# Print the reshaped array
print(reshaped_array)

# Print the number of dimensions of the reshaped array (ndim)
print(reshaped_array.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [17]:
import numpy as np

# Create a 2D array with shape (2, 4)
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

# Print the original 2D array
print(arr_2d)

# Print the number of dimensions of the original 2D array
print(arr_2d.ndim)

# Flatten the 2D array into a 1D array
arr_1D = arr_2d.flatten()

# Print the flattened 1D array
print(arr_1D)

# Print the number of dimensions of the flattened 1D array
print(arr_1D.ndim)



[[1 2 3 4]
 [5 6 7 8]]
2
[1 2 3 4 5 6 7 8]
1


In [23]:
import numpy as np  # Importing numpy library

# Create a 2D array with shape (2, 4)
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

# Print the original 2D array
print(arr_2d)

# Print the number of dimensions of the original 2D array
print(arr_2d.ndim)

# Transpose the 2D array (swap rows and columns)
transpose_array = arr_2d.transpose()

# Print the transposed array
print(transpose_array)

# Print the number of dimensions of the transposed array
print(transpose_array.ndim)


[[1 2 3 4]
 [5 6 7 8]]
2
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
2


In [28]:
import numpy as np  # Importing the numpy library

# Create a 1D numpy array with 15 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

# Print the original array
print(arr)

# Split the array into 3 equal-sized sub-arrays
# The array has 15 elements, and we want to split it into 3 sub-arrays.
split_arrays = np.split(arr, 3)

# Print the resulting split arrays
print(split_arrays)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]
