In [12]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,3,3,4,5,4,42,42,33,113,33])

In [3]:
# print unique elements of array
arr = np.array([1,2,3,3,3,4,5,4,42,42,33,113,33])
print(np.unique(arr))

[  1   2   3   4   5  33  42 113]


In [16]:
import numpy as np  # Import NumPy

# Create an array with NaN values
arr = np.array([1, 4, 2, np.nan, 8, np.nan])

# Print the original array
print("Original array:", arr)

# Check for NaN values
result = np.isnan(arr)  # Returns a boolean array

# Print the result
print("Is NaN present?:", result)


Original array: [ 1.  4.  2. nan  8. nan]
Is NaN present?: [False False False  True False  True]


In [20]:
# filtering an array with where clause
arr = np.array([1,10,4,5,19,29,45,35,23,43])
print(arr)
new_arr = np.where(arr>20,100,arr)
print(new_arr)

[ 1 10  4  5 19 29 45 35 23 43]
[  1  10   4   5  19 100 100 100 100 100]


In [25]:
# print indices of  even elements of array
arr = np.array([1,10,4,5,19,29,46,34,23,42])
even_indices = np.where(arr%2==0)
print(even_indices)

(array([1, 2, 6, 7, 9]),)


In [26]:
# # print indices of  odd elements of array
arr = np.array([1,10,4,5,19,29,46,34,23,42])
even_indices = np.where(arr%2!=0)

print(even_indices)

(array([0, 3, 4, 5, 8]),)


In [28]:
# replacing NaN numbers with 0
arr = np.array([1, np.nan, 2, np.nan, 3, 4, np.nan, 5, 6, np.nan])
arr = np.where(np.isnan(arr),0,arr)
print(arr)

[1. 0. 2. 0. 3. 4. 0. 5. 6. 0.]


In [37]:
# Creating a 2D NumPy array (matrix)
matrix = np.array([[1, 2, 3, 4],  
                   [100, 50, 45, 56],  
                   [8, 9, 10, 11]])  

# Using np.where() to replace values greater than 40 with 8
# If a value in 'matrix' is greater than 40, it is replaced with 8, otherwise, it remains the same
new_matrix = np.where(matrix > 40, 8, matrix)  

# Printing the modified matrix
print(new_matrix)  

[[ 1  2  3  4]
 [ 8  8  8  8]
 [ 8  9 10 11]]
