In [1]:
import numpy as np


In [9]:
import numpy as np  # Importing the numpy library

# Create a 1D numpy array with integer values
arr = np.array([1, 3, 10, 11, 19, 20, 35, 23, 212])

# Print the original array
print(arr)

# Print the data type of the elements in the array
print(arr.dtype)

# Convert the integer array to a float array using astype()
brr = arr.astype(float)

# Print the new array (brr) after type conversion
print(brr)

# Print the data type of the elements in the new array (brr)
print(brr.dtype)


[  1   3  10  11  19  20  35  23 212]
int64
[  1.   3.  10.  11.  19.  20.  35.  23. 212.]
float64


In [12]:
brr = np.array([10,20,30,40,50,60],dtype = "f")
print(brr)
print(brr.dtype)

[10. 20. 30. 40. 50. 60.]
float32


In [14]:
arr = np.array(["a","b",3,4,5])
print(arr.dtype)
# This is because numpy upcasts the data type to accommodate 
# both string and integer types, and it chooses dtype='<U21' to store the data as strings

<U21
