In [1]:
import numpy as np

In [2]:
# creating array with only zero values
zeros_array = np.zeros(20)
print(zeros_array)
      

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# creating numpy array with only ones
_ones_ = np.ones(10)
print(_ones_)
print(type(_ones_))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [7]:
# creating a numpy array with a range  np.arange(starts,ends,step)
_range_array = np.arange(0,16,2)
print(_range_array)

[ 0  2  4  6  8 10 12 14]


In [8]:
# Create an array of 10 evenly spaced values between 1 and 20
_array_ = np.linspace(1, 20, 10)

# Print the created array
print(_array_)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [10]:
# creates an array with  interval[0,1) 0 is includes but 1 is excluded
_random_array = np.random.random(15)
print(_random_array)
print(len(_random_array))

[0.62825278 0.16574054 0.86216193 0.67131878 0.93170471 0.89029799
 0.96409668 0.72757905 0.93934585 0.95630817 0.25818024 0.49506952
 0.12797693 0.86610294 0.47335328]
15


In [11]:
import numpy as np  # Importing the numpy library to work with arrays and mathematical functions

# Generate 5 random values from a normal distribution
# loc = 0: This is the mean of the distribution (the center of the bell curve).
# scale = 1: This is the standard deviation, controlling the spread of the values (how wide or narrow the bell curve is).
# size = 5: This specifies the number of random values we want to generate. In this case, 5 random numbers.
array = np.random.normal(loc=0, scale=1, size=5)

# Print the generated random values
print(array)


[ 0.92775339  0.17733523  0.05583383 -0.26394497  1.23927419]


In [17]:
import numpy as np  # Importing the numpy library for working with arrays and mathematical functions

# Generate 10 random integers between 1 and 10 (excluding 10)
# np.random.randint(low, high, size):
# low = 1: The smallest integer that can be generated (inclusive).
# high = 10: The largest integer that can be generated (exclusive).
# size = 10: The number of random integers to generate. In this case, we want 10 random integers.
array = np.random.randint(1, 10, 10)

# Print the generated array of random integers
print(array)


[4 9 7 8 5 3 8 9 8 7]


In [25]:
import numpy as np  # Importing the numpy library

# Original array from which we will randomly select elements
array = [10, 12, 9, 3, 4, 5, 6, 11, 19, 32, 45, 13]

# Randomly select 5 elements from the array, without replacement
random_array = np.random.choice(array, size=5, replace=False)

# Print the randomly selected array
print(random_array)



[32 19  6  3 10]
